// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chodvuvoaudgfmbovpkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNob2R2dXZvYXVkZ2ZtYm92cGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjU2NTQsImV4cCI6MjA2NjA0MTY1NH0.0T2lyhvplHYqvAs2frAFNUm2NHz3o9QWb1LFC4aPqQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);